from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


SurfaceName = Literal[
    "web",
    "public-token",
    "self-service",
    "bot",
    "local-agent",
    "cli",
    "remote-operation",
    "api",
]
RiskClass = Literal[
    "auth-entry",
    "auth-exit",
    "read-only",
    "secret-adjacent-read",
    "secret-read",
    "public-token-entry",
    "public-token-state-write",
    "public-token-secret-read",
    "state-write",
    "remote-read",
    "remote-exec",
    "destructive",
]
SecretClass = Literal[
    "none",
    "secret-adjacent",
    "client-config-secret",
    "token-raw-issue",
    "public-token",
    "operation-output",
]
ImplementationMode = Literal["inventory-only", "blocked-future", "implemented"]


class SurfacePolicyError(ValueError):
    pass


@dataclass(frozen=True)
class SurfacePolicy:
    policy_id: str
    surface: SurfaceName
    method: str
    path: str
    actor: str
    auth_method: str
    risk_class: RiskClass
    secret_class: SecretClass
    side_effects: tuple[str, ...]
    gates: tuple[str, ...]
    audit_required: bool
    operation_contract: str
    live_retest_required: bool
    implementation_mode: ImplementationMode
    enables_new_behavior: bool
    test_refs: tuple[str, ...]
    notes: str


def _p(
    policy_id: str,
    surface: SurfaceName,
    method: str,
    path: str,
    actor: str,
    auth_method: str,
    risk_class: RiskClass,
    secret_class: SecretClass,
    side_effects: tuple[str, ...],
    gates: tuple[str, ...],
    audit_required: bool,
    operation_contract: str,
    live_retest_required: bool,
    implementation_mode: ImplementationMode,
    test_refs: tuple[str, ...],
    notes: str,
    enables_new_behavior: bool = False,
) -> SurfacePolicy:
    return SurfacePolicy(
        policy_id=policy_id,
        surface=surface,
        method=method,
        path=path,
        actor=actor,
        auth_method=auth_method,
        risk_class=risk_class,
        secret_class=secret_class,
        side_effects=side_effects,
        gates=gates,
        audit_required=audit_required,
        operation_contract=operation_contract,
        live_retest_required=live_retest_required,
        implementation_mode=implementation_mode,
        enables_new_behavior=enables_new_behavior,
        test_refs=test_refs,
        notes=notes,
    )


SURFACE_POLICIES: tuple[SurfacePolicy, ...] = (
    _p(
        "local_agent.health",
        "local-agent",
        "GET",
        "/agent/health",
        "local-agent-controller",
        "hash-only bearer token + agent:health",
        "read-only",
        "none",
        (),
        ("AgentRoutePolicy first_slice", "audit event"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Health route stays local-agent first slice only.",
    ),
    _p(
        "local_agent.version",
        "local-agent",
        "GET",
        "/agent/version",
        "local-agent-controller",
        "hash-only bearer token + agent:health",
        "read-only",
        "none",
        (),
        ("AgentRoutePolicy first_slice", "audit event"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Version route exposes no secrets.",
    ),
    _p(
        "local_agent.runtime",
        "local-agent",
        "GET",
        "/agent/runtime",
        "local-agent-controller",
        "hash-only bearer token + agent:read",
        "read-only",
        "secret-adjacent",
        (),
        ("AgentRoutePolicy first_slice", "audit event", "no raw secret"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Runtime detection is read-only but remains command-adjacent.",
    ),
    _p(
        "local_agent.protocols",
        "local-agent",
        "GET",
        "/agent/protocols",
        "local-agent-controller",
        "hash-only bearer token + agent:protocols:read",
        "read-only",
        "secret-adjacent",
        (),
        ("AgentRoutePolicy first_slice", "audit event", "no raw secret"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Protocol listing is metadata only.",
    ),
    _p(
        "local_agent.clients.list.blocked",
        "local-agent",
        "GET",
        "/agent/clients",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:read",
        "read-only",
        "secret-adjacent",
        (),
        ("blocked until privacy policy", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Client metadata stays blocked in first production slice.",
    ),
    _p(
        "local_agent.clients.create.blocked",
        "local-agent",
        "POST",
        "/agent/clients",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "state-write",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent write route is exposed by this slice.",
    ),
    _p(
        "local_agent.clients.update.blocked",
        "local-agent",
        "PATCH",
        "/agent/clients/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "state-write",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent write route is exposed by this slice.",
    ),
    _p(
        "local_agent.clients.delete.blocked",
        "local-agent",
        "DELETE",
        "/agent/clients/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "destructive",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent delete route is exposed by this slice.",
    ),
    _p(
        "local_agent.configs.read.blocked",
        "local-agent",
        "GET",
        "/agent/configs/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:configs:read",
        "secret-read",
        "client-config-secret",
        (),
        ("blocked until ownership policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        ".conf, QR and vpn:// stay blocked secret outputs.",
    ),
    _p(
        "local_agent.backup.redacted.blocked",
        "local-agent",
        "GET",
        "/agent/backup/redacted",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:read",
        "secret-read",
        "secret-adjacent",
        (),
        ("blocked until backup policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Even redacted backup needs a separate backup design.",
    ),
    _p(
        "local_agent.backup.full.blocked",
        "local-agent",
        "POST",
        "/agent/backup/full",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:full",
        "secret-read",
        "client-config-secret",
        (),
        ("blocked until backup policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Full backup is secret-bearing and not first slice.",
    ),
    _p(
        "local_agent.restore.blocked",
        "local-agent",
        "POST",
        "/agent/restore",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:restore",
        "destructive",
        "client-config-secret",
        ("local Amnezia state",),
        ("blocked until restore policy", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Restore is destructive and not first slice.",
    ),
    _p(
        "local_agent.reboot.blocked",
        "local-agent",
        "POST",
        "/agent/reboot",
        "local-agent-controller",
        "hash-only bearer token + agent:operations:destructive",
        "destructive",
        "none",
        ("local host runtime",),
        ("blocked until dangerous-operation policy", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Reboot remains out of scope.",
    ),
    _p(
        "api.servers.list",
        "api",
        "GET",
        "/api/servers",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Lists configured server aliases and aggregate readiness only.",
        enables_new_behavior=True,
    ),
    _p(
        "api.servers.summary",
        "api",
        "GET",
        "/api/servers/{server_name}/summary",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Shows one server alias, local health metadata and aggregate counts.",
        enables_new_behavior=True,
    ),
    _p(
        "api.integration.status",
        "api",
        "GET",
        "/api/integration/status",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only integration status route.",
        False,
        "implemented",
        ("tests/api/test_api_integration_status.py",),
        "Reports gate state and aggregate counts without enabling remote writes.",
        enables_new_behavior=True,
    ),
    _p(
        "api.local_agent.runtime_summary",
        "api",
        "GET",
        "/api/local-agent/runtime/summary",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Reports controller-safe Local Agent runtime readiness without host, port, token or runtime command details.",
        enables_new_behavior=True,
    ),
    _p(
        "api.metrics.summary",
        "api",
        "GET",
        "/api/metrics/summary",
        "api-client",
        "bearer token + metrics:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Reports global counts and latest-device traffic totals only.",
        enables_new_behavior=True,
    ),
    _p(
        "api.users.summary",
        "api",
        "GET",
        "/api/users/summary",
        "api-client",
        "bearer token + metrics:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Reports user and order aggregates without personal identifiers.",
        enables_new_behavior=True,
    ),
    _p(
        "api.install.mutation_requests",
        "api",
        "POST",
        "/api/install/mutation-requests",
        "api-client",
        "bearer token + install:write",
        "state-write",
        "none",
        ("admin_actions",),
        (
            "P7-C005",
            "scoped install write contour",
            "audit event",
            "no remote exec",
            "no config delivery",
            "no raw secret",
        ),
        True,
        "Records a P7-C005 install mutation request as safe audit metadata; does not execute installer/apply.",
        True,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Loopback-only first write contour; executor remains out of process and blocked while VPS_APPLY_ENABLED=false.",
        enables_new_behavior=True,
    ),
    _p(
        "api.health.polling.run.blocked",
        "api",
        "POST",
        "/api/health/polling/run",
        "api-client",
        "blocked until scheduler operator token + P6-M002",
        "remote-read",
        "operation-output",
        ("server_health_checks",),
        (
            "P6-M002",
            "live probe gate",
            "read-only command policy",
            "aggregate-only",
            "no raw command output",
            "audit event",
        ),
        True,
        "Future scheduler trigger route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Health polling may only graduate after live probe and raw output boundaries are approved.",
    ),
    _p(
        "api.analytics.users.detail.blocked",
        "api",
        "GET",
        "/api/analytics/users/{id}",
        "api-client",
        "blocked until analytics privacy token + P6-N002",
        "secret-adjacent-read",
        "secret-adjacent",
        (),
        (
            "P6-N002",
            "aggregate-only",
            "no per-user",
            "no raw secret",
            "audit event",
        ),
        True,
        "Future analytics detail route; not mounted by this slice.",
        False,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Per-user analytics remains blocked; only aggregate widgets are allowed.",
    ),
    _p(
        "api.analytics.peers.detail.blocked",
        "api",
        "GET",
        "/api/analytics/peers/{id}",
        "api-client",
        "blocked until analytics privacy token + P6-N002",
        "secret-adjacent-read",
        "secret-adjacent",
        (),
        (
            "P6-N002",
            "aggregate-only",
            "no per-peer",
            "no raw secret",
            "audit event",
        ),
        True,
        "Future analytics detail route; not mounted by this slice.",
        False,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Per-peer analytics remains blocked; only aggregate widgets are allowed.",
    ),
    _p(
        "api.payments.webhook.blocked",
        "api",
        "POST",
        "/api/payments/webhook",
        "payment-provider",
        "blocked until provider signature + replay protection",
        "state-write",
        "secret-adjacent",
        ("orders", "payment_events"),
        (
            "P6-I003",
            "payment processor gate",
            "signature validation",
            "idempotency",
            "manual review remains required",
            "no raw secret",
        ),
        True,
        "Future payment webhook route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Payment provider callbacks cannot create access automatically.",
    ),
    _p(
        "api.entitlements.activate.blocked",
        "api",
        "POST",
        "/api/entitlements/{id}/activate",
        "api-client",
        "blocked until entitlement contract + write gate",
        "state-write",
        "secret-adjacent",
        ("orders", "devices", "remote peers"),
        (
            "P6-I003",
            "P6-C002",
            "P6-C003",
            "config delivery stays blocked",
            "manual approval",
            "audit event",
            "no raw secret",
        ),
        True,
        "Future commercial entitlement activation route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Commercial entitlement must not bypass config/write gates.",
    ),
    _p(
        "api.entitlements.manual_review.blocked",
        "api",
        "POST",
        "/api/entitlements/{id}/manual-review",
        "api-client",
        "blocked until operator token + P6-I006",
        "state-write",
        "secret-adjacent",
        ("orders", "entitlement_audit"),
        (
            "P6-I006",
            "manual review",
            "operator-only approval",
            "no automatic activation",
            "config delivery stays blocked",
            "audit event",
            "no raw secret",
        ),
        True,
        "Future entitlement audit route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Manual entitlement decisions must remain separate from payment and config delivery.",
    ),
    _p(
        "api.config_links.issue.blocked",
        "api",
        "POST",
        "/api/config-links",
        "api-client",
        "blocked until operator token + P6-C002",
        "state-write",
        "token-raw-issue",
        ("config_link_tokens", "admin_actions"),
        (
            "P6-C002",
            "operator-only issue",
            "hash-at-rest",
            "purpose",
            "ttl",
            "one-time",
            "audit event",
            "no raw token",
        ),
        True,
        "Future tokenized config-link issue route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Raw config-link token may only be returned once after a named config delivery gate.",
    ),
    _p(
        "public_token.config_link.redeem.blocked",
        "public-token",
        "GET",
        "/c/{token}",
        "public-token-holder",
        "raw token + stored hash lookup",
        "public-token-secret-read",
        "client-config-secret",
        ("config delivery",),
        (
            "P6-C002",
            "purpose",
            "ttl",
            "one-time",
            "user/device binding",
            "rate limit candidate",
            "audit event",
            "redaction",
            "no raw token",
            "no raw secret",
        ),
        True,
        "Future tokenized config-link redeem route; not mounted by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Redeeming a short link is secret-bearing config delivery and remains gated.",
    ),
    _p(
        "web.auth.login_submit",
        "web",
        "POST",
        "/login",
        "public",
        "password form + session cookie",
        "auth-entry",
        "secret-adjacent",
        ("session",),
        ("csrf", "generic errors", "rate limit candidate", "no raw secret"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_app.py",),
        "Login audit/rate-limit are follow-up policy work.",
    ),
    _p(
        "web.auth.logout",
        "web",
        "POST",
        "/logout",
        "web-admin",
        "session",
        "auth-exit",
        "none",
        ("session",),
        ("csrf", "session required"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_app.py",),
        "Logout is current web session behavior.",
    ),
    _p(
        "web.api_readiness.index",
        "web",
        "GET",
        "/api-readiness",
        "web-admin",
        "session",
        "read-only",
        "none",
        (),
        ("session required", "aggregate-only", "no raw secret"),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_api_readiness.py",),
        "Web-admin view of the verified read-only API baseline.",
    ),
    _p(
        "web.integration_status.index",
        "web",
        "GET",
        "/integration-status",
        "web-admin",
        "session",
        "read-only",
        "none",
        (),
        ("session required", "aggregate-only", "no raw secret", "no SSH"),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_web_integration_status.py",),
        "Web-admin view of post-dry-run integration gates without enabling remote writes.",
    ),
    _p(
        "web.api_tokens.index",
        "web",
        "GET",
        "/api-tokens",
        "web-admin",
        "session",
        "read-only",
        "secret-adjacent",
        (),
        ("session required", "metadata only", "no token hash", "no raw token"),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py",),
        "Lists scoped API token metadata without token hashes or raw tokens.",
    ),
    _p(
        "web.api_tokens.issue",
        "web",
        "POST",
        "/api-tokens/issue",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("api_tokens", "admin_actions"),
        ("csrf", "session required", "scope allowlist", "one-time raw token display"),
        True,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py", "tests/services/test_api_tokens.py"),
        "Issues first-slice route API tokens with raw token shown once only.",
    ),
    _p(
        "web.api_tokens.revoke",
        "web",
        "POST",
        "/api-tokens/{token_id}/revoke",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("api_tokens", "admin_actions"),
        ("csrf", "session required", "safe audit metadata"),
        True,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py", "tests/services/test_api_tokens.py"),
        "Revokes scoped API tokens without secret output.",
    ),
    _p(
        "web.api_tokens.rotate",
        "web",
        "POST",
        "/api-tokens/{token_id}/rotate",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("api_tokens", "admin_actions"),
        (
            "csrf",
            "session required",
            "scope preservation",
            "integration identity preservation",
            "one-time raw token display",
        ),
        True,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py", "tests/services/test_api_tokens.py"),
        "Rotates an integration credential while preserving owner, purpose and scopes.",
    ),
    _p(
        "web.config_templates.save",
        "web",
        "POST",
        "/config-templates/{config_version}/save",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("config template state",),
        ("csrf", "session required", "synthetic preview", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_config_templates.py",),
        "Template changes can affect future generated configs.",
    ),
    _p(
        "web.config_templates.reset",
        "web",
        "POST",
        "/config-templates/{config_version}/reset",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("config template state",),
        ("csrf", "session required", "synthetic preview", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_config_templates.py",),
        "Template reset can affect future generated configs.",
    ),
    _p(
        "web.device_passports.index",
        "web",
        "GET",
        "/device-passports",
        "web-admin",
        "session",
        "secret-adjacent-read",
        "secret-adjacent",
        (),
        (
            "session required",
            "safe metadata only",
            "no raw config/private key/PSK/ticket secret/token hash",
            "no remote observation",
            "no DB mutation",
        ),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_device_passports.py",),
        "Authenticated bounded Device Passport inventory view.",
        enables_new_behavior=True,
    ),
    _p(
        "web.device_passports.detail",
        "web",
        "GET",
        "/device-passports/{device_id}",
        "web-admin",
        "session",
        "secret-adjacent-read",
        "secret-adjacent",
        (),
        (
            "session required",
            "safe metadata only",
            "no raw config/private key/PSK/ticket secret/token hash",
            "no remote observation",
            "no DB mutation",
            "fixed 404",
        ),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_device_passports.py",),
        "Authenticated Device Passport lifecycle and drift detail view.",
        enables_new_behavior=True,
    ),
    _p(
        "web.device_passports.config_secret",
        "web",
        "GET",
        "/device-passports/{device_id}/config",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        ("config_secret_viewed audit event",),
        (
            "session required",
            "exact device-passport/local-device boundary",
            "secret-safe audit required before response",
            "audit metadata IDs only",
            "redaction",
            "no raw secret",
            "no raw config/private key/PSK/QR payload in audit/logs/errors",
            "no SSH",
            "no remote observation",
            "no live mutation",
        ),
        True,
        "Authenticated admin read of existing client config material only.",
        False,
        "implemented",
        ("tests/web/test_device_passports.py",),
        "Secret bytes are returned only to the authenticated response and never persisted by this route.",
        enables_new_behavior=True,
    ),
    _p(
        "web.device_passports.qr_secret",
        "web",
        "GET",
        "/device-passports/{device_id}/qr",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        ("config_secret_viewed audit event",),
        (
            "session required",
            "exact device-passport/local-device boundary",
            "secret-safe audit required before response",
            "audit metadata IDs only",
            "redaction",
            "no raw secret",
            "no raw config/private key/PSK/QR payload in audit/logs/errors",
            "no SSH",
            "no remote observation",
            "no live mutation",
        ),
        True,
        "Authenticated admin read of an existing client config QR only.",
        False,
        "implemented",
        ("tests/web/test_device_passports.py",),
        "QR bytes are returned only to the authenticated response and never persisted by this route.",
        enables_new_behavior=True,
    ),
    _p(
        "web.users.create",
        "web",
        "POST",
        "/users/new",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required", "validation"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current admin user creation route.",
    ),
    _p(
        "web.plans.device_quota_update",
        "web",
        "POST",
        "/plans/{plan_id}/device-quota",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("plans.max_devices", "admin_actions"),
        ("csrf", "session required", "positive integer validation", "audit event"),
        True,
        "Plan quota changes affect future dedicated-device order approvals only.",
        False,
        "implemented",
        ("tests/web/test_plan_device_quotas.py",),
        "An empty value restores the global MAX_DEVICES_PER_USER fallback.",
        enables_new_behavior=True,
    ),
    _p(
        "web.users.update",
        "web",
        "POST",
        "/users/{user_id}/edit",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required", "validation"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current admin user update route.",
    ),
    _p(
        "web.users.block",
        "web",
        "POST",
        "/users/{user_id}/block",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current user block route.",
    ),
    _p(
        "web.users.delete",
        "web",
        "POST",
        "/users/{user_id}/delete",
        "web-admin",
        "session",
        "destructive",
        "secret-adjacent",
        ("users", "devices", "admin_actions"),
        ("csrf", "session required", "explicit confirmation candidate"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Existing route is inventoried; future UX can add stronger confirmation.",
    ),
    _p(
        "web.users.disable_vpn",
        "web",
        "POST",
        "/users/{user_id}/disable-vpn",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        (
            "devices",
            "device_passports",
            "device_enrollment_tickets",
            "email_recovery_tokens",
            "orders",
            "remote peers",
            "admin_actions",
        ),
        (
            "csrf",
            "session required",
            "remote-first OperationPlan",
            "VPS apply gate",
            "cascade revoke",
            "redaction",
        ),
        True,
        "Verified live VPS disable flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py", "tests/server/test_peer_apply.py"),
        "Any behavior change requires live retest.",
    ),
    _p(
        "web.users.enable_vpn",
        "web",
        "POST",
        "/users/{user_id}/enable-vpn",
        "web-admin",
        "session",
        "remote-exec",
        "client-config-secret",
        ("devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction", "no raw secret"),
        True,
        "Verified live VPS enable/apply flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py", "tests/server/test_peer_apply.py"),
        "Any behavior change requires live retest.",
    ),
    _p(
        "web.devices.create_operator",
        "web",
        "POST",
        "/users/{user_id}/devices/create-operator",
        "web-admin",
        "session + configured operator admin actor",
        "remote-exec",
        "client-config-secret",
        ("devices", "remote peers", "private config artifact", "admin_actions"),
        (
            "csrf",
            "session required",
            "active owner",
            "authorized admin actor",
            "VPS_APPLY_ENABLED",
            "OPERATOR_DEVICE_CREATE_ENABLED",
            "exact one-device confirmation",
            "operation contract",
            "atomic POSIX 0600 artifact",
            "redaction",
            "no raw secret",
        ),
        True,
        "AccessService.create_operator_device remote-first partial-failure contract.",
        True,
        "implemented",
        (
            "tests/web/test_operator_device_create.py",
            "tests/cli/test_operator_device_create.py",
            "tests/services/test_access_service.py",
        ),
        "Private operator-only adapter; dry-run is side-effect free and apply uses two default-false runtime gates.",
    ),
    _p(
        "web.devices.secrets",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/secrets",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        (),
        ("csrf", "session required", "user/device match", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py", "tests/services/test_config_delivery.py"),
        "Config artifacts are client-config-secret.",
    ),
    _p(
        "web.devices.delete",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/delete",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction"),
        True,
        "Physical-device cascade revoke refuses local-only deletion while a remote peer may remain.",
        True,
        "inventory-only",
        (
            "tests/web/test_users.py",
            "tests/server/test_peer_apply.py",
            "tests/services/test_device_revoke.py",
        ),
        "Any remote behavior change requires live retest; reconnect observations never reactivate access.",
    ),
    _p(
        "web.users.destroy",
        "web",
        "POST",
        "/users/{user_id}/destroy",
        "web-admin",
        "session",
        "destructive",
        "operation-output",
        ("users", "devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "explicit confirmation candidate", "operation contract", "redaction"),
        True,
        "Current destructive web route; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Future API must split preview/apply/recovery.",
    ),
    _p(
        "web.email.config_send",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/email-config",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        (),
        ("csrf", "session required", "user/device match", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Email config delivery sends real .conf/QR/vpn:// artifacts.",
    ),
    _p(
        "web.email.verify_start",
        "web",
        "POST",
        "/users/{user_id}/email/verify/start",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("email verification tokens", "admin_actions"),
        ("csrf", "session required", "token hash storage", "audit event", "no raw token"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Raw verification token must not be persisted or audited.",
    ),
    _p(
        "web.email.recovery_start",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/email-recovery/start",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("email recovery tokens", "admin_actions"),
        ("csrf", "session required", "token hash storage", "audit event", "no raw token"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Raw recovery token must not be persisted or audited.",
    ),
    _p(
        "public_token.email_verify_submit",
        "public-token",
        "POST",
        "/email/verify",
        "public-token-holder",
        "raw token + stored hash lookup",
        "public-token-state-write",
        "public-token",
        ("email verification state",),
        ("purpose", "ttl", "one-time", "generic errors", "no raw token"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Public token is purpose-bound, not admin auth.",
    ),
    _p(
        "public_token.email_recover_submit",
        "public-token",
        "POST",
        "/email/recover",
        "public-token-holder",
        "raw token + stored hash lookup",
        "public-token-secret-read",
        "client-config-secret",
        (),
        (
            "purpose",
            "ttl",
            "one-time",
            "user/device binding",
            "rate limit candidate",
            "audit event",
            "redaction",
            "no raw token",
        ),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Public token can release config secret only through strict one-time recovery.",
    ),
    _p(
        "self_service.dashboard.blocked",
        "self-service",
        "GET",
        "/self-service",
        "self-service-user",
        "separate self-service auth + own-account boundary",
        "read-only",
        "none",
        (),
        (
            "P6-C001",
            "admin surface separated",
            "own-account only",
            "aggregate-only",
            "no raw secret",
        ),
        True,
        "",
        False,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Future user dashboard must not reuse web-admin routes or auth.",
    ),
    _p(
        "self_service.config_delivery.blocked",
        "self-service",
        "POST",
        "/self-service/devices/{device_id}/config",
        "self-service-user",
        "separate self-service auth + own-device boundary",
        "secret-read",
        "client-config-secret",
        (),
        (
            "P6-C001",
            "P6-C002",
            "admin surface separated",
            "own-device only",
            "ttl",
            "one-time",
            "audit event",
            "redaction",
            "no raw secret",
        ),
        True,
        "",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Future config delivery is secret-bearing and needs a config delivery gate.",
    ),
    _p(
        "self_service.device_revoke.blocked",
        "self-service",
        "POST",
        "/self-service/devices/{device_id}/revoke",
        "self-service-user",
        "separate self-service auth + own-device boundary",
        "remote-exec",
        "operation-output",
        ("owned device", "remote peers"),
        (
            "P6-C001",
            "P6-C003",
            "admin surface separated",
            "own-device only",
            "operation contract",
            "audit event",
            "redaction",
        ),
        True,
        "Future self-service revoke requires operation queue, idempotency and rollback policy.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Future self-service revoke is a production mutation and remains gated.",
    ),
    _p(
        "web.servers.create",
        "web",
        "POST",
        "/servers/new",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("servers", "admin_actions"),
        ("csrf", "session required", "validation", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Server connection fields remain secret-adjacent.",
    ),
    _p(
        "web.servers.update",
        "web",
        "POST",
        "/servers/{server_id}/edit",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("servers", "admin_actions"),
        ("csrf", "session required", "validation", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Server runtime/config changes can affect live behavior.",
    ),
    _p(
        "web.servers.disable",
        "web",
        "POST",
        "/servers/{server_id}/disable",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("servers", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Disables local server record.",
    ),
    _p(
        "web.servers.sync_run",
        "web",
        "POST",
        "/servers/{server_id}/sync/run",
        "web-admin",
        "session",
        "remote-read",
        "operation-output",
        ("peer sync snapshots", "admin_actions"),
        ("csrf", "session required", "read-only command policy", "redaction"),
        True,
        "Existing peer sync reads live VPS state and renders safe ReconciliationSnapshot diagnostics.",
        True,
        "inventory-only",
        (
            "tests/web/test_servers.py",
            "tests/services/test_peer_inventory.py",
            "tests/services/test_drift_diagnostics.py",
        ),
        "Read-only diagnostics expose desired, observed, drift, freshness, reason, evidence count and safe next action; classification changes require live retest.",
    ),
    _p(
        "web.servers.unknown_peers.ignore",
        "web",
        "POST",
        "/servers/{server_id}/unknown-peers/ignore",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("peer sync ignore state", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Local ignore marker only.",
    ),
    _p(
        "web.servers.amnezia_peers.unmark",
        "web",
        "POST",
        "/servers/{server_id}/amnezia-peers/unmark",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("peer sync ignore state", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Local unignore marker only.",
    ),
    _p(
        "web.servers.unknown_peers.remove",
        "web",
        "POST",
        "/servers/{server_id}/unknown-peers/remove",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        ("remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction"),
        True,
        "Existing live VPS remove flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_servers.py", "tests/server/test_peer_apply.py"),
        "Removing external peers requires careful confirmation in future API.",
    ),
    _p(
        "web.servers.missing_devices.add",
        "web",
        "POST",
        "/servers/{server_id}/missing-devices/{device_id}/add",
        "web-admin",
        "session",
        "remote-exec",
        "client-config-secret",
        ("remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction", "no raw secret"),
        True,
        "Existing live VPS add missing local device flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_servers.py", "tests/server/test_peer_apply.py"),
        "Adding a peer writes live VPS state.",
    ),
    _p(
        "web.servers.health_run",
        "web",
        "POST",
        "/servers/{server_id}/health/run",
        "web-admin",
        "session",
        "remote-read",
        "operation-output",
        ("server_health_checks", "admin_actions"),
        ("csrf", "session required", "read-only command policy", "redaction"),
        True,
        "RemoteOperationRunner read-only health check.",
        False,
        "inventory-only",
        ("tests/server/test_operation_runner.py", "tests/web/test_servers.py"),
        "Canonical read-only remote operation model.",
    ),
    _p(
        "bot.admin.status",
        "bot",
        "ACTION",
        "ADMIN_STATUS_CALLBACK",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "read-only",
        "none",
        ("admin_actions",),
        (
            "workflow.is_admin",
            "aggregate-only",
            "safe audit metadata",
            "no raw secret",
            "no SSH",
        ),
        True,
        "Local repository aggregate status only.",
        False,
        "implemented",
        (
            "tests/services/test_operator_status.py",
            "tests/bot/test_bot_handlers.py",
            "tests/bot/test_bot_workflows.py",
        ),
        "Authorized operator status without remote polling or secret-bearing output.",
    ),
    _p(
        "bot.admin.integrations",
        "bot",
        "ACTION",
        "ADMIN_INTEGRATIONS_CALLBACK",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "secret-adjacent-read",
        "secret-adjacent",
        ("admin_actions",),
        (
            "workflow.is_admin",
            "typed hash-free allowlist",
            "lifecycle read only",
            "safe count-only audit metadata",
            "no raw token or token hash",
            "no issue rotate revoke",
        ),
        True,
        "Existing hash-free local integration registry query only.",
        False,
        "implemented",
        (
            "tests/services/test_operator_credential_status.py",
            "tests/bot/test_bot_handlers.py",
            "tests/bot/test_bot_workflows.py",
        ),
        "Authorized credential lifecycle visibility without credential mutation.",
    ),
    _p(
        "bot.admin.servers",
        "bot",
        "ACTION",
        "ADMIN_SERVERS_CALLBACK",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "read-only",
        "none",
        ("admin_actions",),
        (
            "workflow.is_admin",
            "typed safe summary allowlist",
            "stored health only",
            "safe count-only audit metadata",
            "no host or key fields",
            "no SSH",
        ),
        True,
        "Existing local API-safe server summary query only.",
        False,
        "implemented",
        (
            "tests/services/test_operator_server_status.py",
            "tests/bot/test_bot_handlers.py",
            "tests/bot/test_bot_workflows.py",
        ),
        "Authorized stored server health without remote polling or secret fields.",
    ),
    _p(
        "bot.admin.traffic",
        "bot",
        "ACTION",
        "ADMIN_TRAFFIC_CALLBACK",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "read-only",
        "none",
        ("admin_actions",),
        (
            "workflow.is_admin",
            "local traffic snapshots only",
            "safe count-only audit metadata",
            "no config material",
            "no SSH",
        ),
        True,
        "Local repository active-device traffic snapshot view only.",
        False,
        "implemented",
        (
            "tests/bot/test_bot_handlers.py",
            "tests/bot/test_bot_workflows.py",
        ),
        "Authorized traffic visibility without remote polling or secret-bearing output.",
    ),
    _p(
        "bot.admin.approve_order",
        "bot",
        "ACTION",
        "ADMIN_APPROVE_PREFIX callback",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "remote-exec",
        "client-config-secret",
        ("orders", "devices", "remote peers", "admin_actions"),
        ("workflow.is_admin", "operation contract", "audit event", "redaction", "no raw secret"),
        True,
        "Verified live VPS approve/apply flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Verified baseline behavior contract.",
    ),
    _p(
        "bot.support.runtime.blocked",
        "bot",
        "COMMAND",
        "support bot runtime",
        "telegram-support-user",
        "separate Telegram token + support runtime gate",
        "read-only",
        "none",
        (),
        (
            "P6-I004",
            "separate Telegram token",
            "support data-retention gate",
            "no config output",
            "no access-bot callback reuse",
        ),
        True,
        "Future support bot runtime; not started by this slice.",
        False,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Support bot may provide intake/help only after a separate gate.",
    ),
    _p(
        "bot.news.runtime.blocked",
        "bot",
        "COMMAND",
        "news bot runtime",
        "telegram-news-subscriber",
        "separate Telegram token + broadcast gate",
        "read-only",
        "none",
        (),
        (
            "P6-I004",
            "separate Telegram token",
            "broadcast gate",
            "no user/device state",
            "no config output",
        ),
        True,
        "Future news bot runtime; not started by this slice.",
        False,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "News bot is announcements-only and cannot touch VPN state.",
    ),
    _p(
        "bot.access.profile_icon.apply.blocked",
        "bot",
        "ACTION",
        "access bot profile icon apply",
        "operator",
        "blocked until Telegram identity mutation gate",
        "state-write",
        "token-raw-issue",
        ("telegram bot identity",),
        (
            "P6-I005",
            "Telegram identity mutation gate",
            "operator approval",
            "no live bot send",
            "no raw token evidence",
        ),
        True,
        "Future access bot profile icon apply; no Telegram API call by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Profile icon apply is a Telegram-side identity mutation.",
    ),
    _p(
        "bot.support.profile_icon.apply.blocked",
        "bot",
        "ACTION",
        "support bot profile icon apply",
        "operator",
        "blocked until Telegram identity mutation gate",
        "state-write",
        "token-raw-issue",
        ("telegram bot identity",),
        (
            "P6-I005",
            "Telegram identity mutation gate",
            "operator approval",
            "no live bot send",
            "no raw token evidence",
        ),
        True,
        "Future support bot profile icon apply; no Telegram API call by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Profile icon apply is a Telegram-side identity mutation.",
    ),
    _p(
        "bot.news.profile_icon.apply.blocked",
        "bot",
        "ACTION",
        "news bot profile icon apply",
        "operator",
        "blocked until Telegram identity mutation gate",
        "state-write",
        "token-raw-issue",
        ("telegram bot identity",),
        (
            "P6-I005",
            "Telegram identity mutation gate",
            "operator approval",
            "no live bot send",
            "no raw token evidence",
        ),
        True,
        "Future news bot profile icon apply; no Telegram API call by this slice.",
        True,
        "blocked-future",
        ("tests/security/test_surface_policy.py",),
        "Profile icon apply is a Telegram-side identity mutation.",
    ),
    _p(
        "bot.admin.config_resend",
        "bot",
        "ACTION",
        "ADMIN_RESEND_PREFIX callback",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "secret-read",
        "client-config-secret",
        (),
        ("workflow.is_admin", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py", "tests/bot/test_delivery.py"),
        "Admin resend emits config artifacts.",
    ),
    _p(
        "bot.user.config_resend",
        "bot",
        "ACTION",
        "USER_RESEND_PREFIX callback",
        "telegram-user",
        "Telegram identity + get_user_device ownership",
        "secret-read",
        "client-config-secret",
        (),
        ("ownership", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py", "tests/bot/test_delivery.py"),
        "User resend must remain own-device only.",
    ),
    _p(
        "bot.user.device_revoke",
        "bot",
        "ACTION",
        "USER_REVOKE_CONFIRM_PREFIX callback",
        "telegram-user",
        "Telegram identity + get_user_device ownership",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers"),
        ("ownership", "operation contract", "audit event", "redaction"),
        True,
        "Existing revoke flow removes remote peer before local revoke when configured.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Partial failure policy blocks broader API expansion.",
    ),
    _p(
        "bot.user.devices_reset",
        "bot",
        "ACTION",
        "USER_RESET_DEVICES_CONFIRM_CALLBACK",
        "telegram-user",
        "Telegram identity + user ownership",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers"),
        ("ownership", "operation contract", "audit event", "redaction"),
        True,
        "Existing reset iterates owned devices; not generalized API.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Needs explicit partial-failure recovery before broader write API.",
    ),
    _p(
        "remote.server.health_check",
        "remote-operation",
        "OPERATION",
        "server.health.check",
        "web-admin or cli-operator or system",
        "session, cli or system",
        "remote-read",
        "operation-output",
        ("server_health_checks",),
        ("read-only command policy", "redaction", "no raw secret"),
        True,
        "RemoteOperationRunner read-only health check.",
        False,
        "inventory-only",
        ("tests/server/test_operation_runner.py", "tests/server/test_checks.py"),
        "First runner slice remains read-only.",
    ),
    _p(
        "cli.server.apply_peer_live",
        "cli",
        "COMMAND",
        "server apply-peer --apply",
        "cli-operator",
        "local shell",
        "remote-exec",
        "client-config-secret",
        ("remote peers",),
        ("explicit apply", "operation contract", "redaction", "no raw secret"),
        True,
        "Existing CLI live apply path; not future generic API.",
        True,
        "inventory-only",
        ("tests/server/test_peer_apply.py",),
        "Any behavior change requires live retest.",
    ),
    _p(
        "cli.server.revoke_peer_live",
        "cli",
        "COMMAND",
        "server revoke-peer --apply",
        "cli-operator",
        "local shell",
        "remote-exec",
        "operation-output",
        ("remote peers",),
        ("explicit apply", "operation contract", "redaction"),
        True,
        "Existing CLI live revoke path; not future generic API.",
        True,
        "inventory-only",
        ("tests/server/test_peer_apply.py",),
        "Any behavior change requires live retest.",
    ),
)


def get_surface_policy(policy_id: str) -> SurfacePolicy:
    for policy in SURFACE_POLICIES:
        if policy.policy_id == policy_id:
            return policy
    raise SurfacePolicyError(f"No surface policy for {policy_id}")


def policies_by_surface(surface: SurfaceName) -> tuple[SurfacePolicy, ...]:
    return tuple(policy for policy in SURFACE_POLICIES if policy.surface == surface)
