from __future__ import annotations

from pathlib import Path


BOT_ASSETS_DIR = Path(__file__).with_name("assets")
BOT_START_HEADER_IMAGE_NAME = "NEOBYATNAYA-AMNZ-BOT.png"
BOT_START_HEADER_IMAGE_PATH = BOT_ASSETS_DIR / BOT_START_HEADER_IMAGE_NAME
BOT_LANGUAGE_SELECTION_HEADER_IMAGE_NAME = (
    "NEOBYATNAYA-AMNZ-LANGUAGE-HEADER.png"
)
BOT_LANGUAGE_SELECTION_HEADER_IMAGE_PATH = (
    BOT_ASSETS_DIR / BOT_LANGUAGE_SELECTION_HEADER_IMAGE_NAME
)
