from __future__ import annotations

from dataclasses import dataclass
from typing import Literal


SurfaceName = Literal[
    "web",
    "public-token",
    "bot",
    "local-agent",
    "cli",
    "remote-operation",
    "api",
]
RiskClass = Literal[
    "auth-entry",
    "auth-exit",
    "read-only",
    "secret-adjacent-read",
    "secret-read",
    "public-token-entry",
    "public-token-state-write",
    "public-token-secret-read",
    "state-write",
    "remote-read",
    "remote-exec",
    "destructive",
]
SecretClass = Literal[
    "none",
    "secret-adjacent",
    "client-config-secret",
    "token-raw-issue",
    "public-token",
    "operation-output",
]
ImplementationMode = Literal["inventory-only", "blocked-future", "implemented"]


class SurfacePolicyError(ValueError):
    pass


@dataclass(frozen=True)
class SurfacePolicy:
    policy_id: str
    surface: SurfaceName
    method: str
    path: str
    actor: str
    auth_method: str
    risk_class: RiskClass
    secret_class: SecretClass
    side_effects: tuple[str, ...]
    gates: tuple[str, ...]
    audit_required: bool
    operation_contract: str
    live_retest_required: bool
    implementation_mode: ImplementationMode
    enables_new_behavior: bool
    test_refs: tuple[str, ...]
    notes: str


def _p(
    policy_id: str,
    surface: SurfaceName,
    method: str,
    path: str,
    actor: str,
    auth_method: str,
    risk_class: RiskClass,
    secret_class: SecretClass,
    side_effects: tuple[str, ...],
    gates: tuple[str, ...],
    audit_required: bool,
    operation_contract: str,
    live_retest_required: bool,
    implementation_mode: ImplementationMode,
    test_refs: tuple[str, ...],
    notes: str,
    enables_new_behavior: bool = False,
) -> SurfacePolicy:
    return SurfacePolicy(
        policy_id=policy_id,
        surface=surface,
        method=method,
        path=path,
        actor=actor,
        auth_method=auth_method,
        risk_class=risk_class,
        secret_class=secret_class,
        side_effects=side_effects,
        gates=gates,
        audit_required=audit_required,
        operation_contract=operation_contract,
        live_retest_required=live_retest_required,
        implementation_mode=implementation_mode,
        enables_new_behavior=enables_new_behavior,
        test_refs=test_refs,
        notes=notes,
    )


SURFACE_POLICIES: tuple[SurfacePolicy, ...] = (
    _p(
        "local_agent.health",
        "local-agent",
        "GET",
        "/agent/health",
        "local-agent-controller",
        "hash-only bearer token + agent:health",
        "read-only",
        "none",
        (),
        ("AgentRoutePolicy first_slice", "audit event"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Health route stays local-agent first slice only.",
    ),
    _p(
        "local_agent.version",
        "local-agent",
        "GET",
        "/agent/version",
        "local-agent-controller",
        "hash-only bearer token + agent:health",
        "read-only",
        "none",
        (),
        ("AgentRoutePolicy first_slice", "audit event"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Version route exposes no secrets.",
    ),
    _p(
        "local_agent.runtime",
        "local-agent",
        "GET",
        "/agent/runtime",
        "local-agent-controller",
        "hash-only bearer token + agent:read",
        "read-only",
        "secret-adjacent",
        (),
        ("AgentRoutePolicy first_slice", "audit event", "no raw secret"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Runtime detection is read-only but remains command-adjacent.",
    ),
    _p(
        "local_agent.protocols",
        "local-agent",
        "GET",
        "/agent/protocols",
        "local-agent-controller",
        "hash-only bearer token + agent:protocols:read",
        "read-only",
        "secret-adjacent",
        (),
        ("AgentRoutePolicy first_slice", "audit event", "no raw secret"),
        True,
        "Existing app.agent.policy first-slice route.",
        False,
        "inventory-only",
        ("tests/agent/test_policy.py",),
        "Protocol listing is metadata only.",
    ),
    _p(
        "local_agent.clients.list.blocked",
        "local-agent",
        "GET",
        "/agent/clients",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:read",
        "read-only",
        "secret-adjacent",
        (),
        ("blocked until privacy policy", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Client metadata stays blocked in first production slice.",
    ),
    _p(
        "local_agent.clients.create.blocked",
        "local-agent",
        "POST",
        "/agent/clients",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "state-write",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent write route is exposed by this slice.",
    ),
    _p(
        "local_agent.clients.update.blocked",
        "local-agent",
        "PATCH",
        "/agent/clients/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "state-write",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "audit event", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent write route is exposed by this slice.",
    ),
    _p(
        "local_agent.clients.delete.blocked",
        "local-agent",
        "DELETE",
        "/agent/clients/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:clients:write",
        "destructive",
        "secret-adjacent",
        ("local client state",),
        ("blocked until operation contract", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "No local-agent delete route is exposed by this slice.",
    ),
    _p(
        "local_agent.configs.read.blocked",
        "local-agent",
        "GET",
        "/agent/configs/{id}",
        "local-agent-controller",
        "hash-only bearer token + agent:configs:read",
        "secret-read",
        "client-config-secret",
        (),
        ("blocked until ownership policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        ".conf, QR and vpn:// stay blocked secret outputs.",
    ),
    _p(
        "local_agent.backup.redacted.blocked",
        "local-agent",
        "GET",
        "/agent/backup/redacted",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:read",
        "secret-read",
        "secret-adjacent",
        (),
        ("blocked until backup policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Even redacted backup needs a separate backup design.",
    ),
    _p(
        "local_agent.backup.full.blocked",
        "local-agent",
        "POST",
        "/agent/backup/full",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:full",
        "secret-read",
        "client-config-secret",
        (),
        ("blocked until backup policy", "audit event", "redaction", "no raw secret"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        False,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Full backup is secret-bearing and not first slice.",
    ),
    _p(
        "local_agent.restore.blocked",
        "local-agent",
        "POST",
        "/agent/restore",
        "local-agent-controller",
        "hash-only bearer token + agent:backup:restore",
        "destructive",
        "client-config-secret",
        ("local Amnezia state",),
        ("blocked until restore policy", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Restore is destructive and not first slice.",
    ),
    _p(
        "local_agent.reboot.blocked",
        "local-agent",
        "POST",
        "/agent/reboot",
        "local-agent-controller",
        "hash-only bearer token + agent:operations:destructive",
        "destructive",
        "none",
        ("local host runtime",),
        ("blocked until dangerous-operation policy", "explicit confirmation", "audit event"),
        True,
        "Future route exists only as app.agent.policy blocked record.",
        True,
        "blocked-future",
        ("tests/agent/test_policy.py",),
        "Reboot remains out of scope.",
    ),
    _p(
        "api.servers.list",
        "api",
        "GET",
        "/api/servers",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Lists configured server aliases and aggregate readiness only.",
        enables_new_behavior=True,
    ),
    _p(
        "api.servers.summary",
        "api",
        "GET",
        "/api/servers/{server_name}/summary",
        "api-client",
        "bearer token + server:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Shows one server alias, local health metadata and aggregate counts.",
        enables_new_behavior=True,
    ),
    _p(
        "api.metrics.summary",
        "api",
        "GET",
        "/api/metrics/summary",
        "api-client",
        "bearer token + metrics:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Reports global counts and latest-device traffic totals only.",
        enables_new_behavior=True,
    ),
    _p(
        "api.users.summary",
        "api",
        "GET",
        "/api/users/summary",
        "api-client",
        "bearer token + metrics:read",
        "read-only",
        "none",
        (),
        ("scoped API token", "aggregate-only", "audit event", "no raw secret", "no SSH"),
        True,
        "Native amn2 read-only API route shell.",
        False,
        "implemented",
        ("tests/api/test_app.py", "tests/services/test_api_tokens.py"),
        "Reports user and order aggregates without personal identifiers.",
        enables_new_behavior=True,
    ),
    _p(
        "web.auth.login_submit",
        "web",
        "POST",
        "/login",
        "public",
        "password form + session cookie",
        "auth-entry",
        "secret-adjacent",
        ("session",),
        ("csrf", "generic errors", "rate limit candidate", "no raw secret"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_app.py",),
        "Login audit/rate-limit are follow-up policy work.",
    ),
    _p(
        "web.auth.logout",
        "web",
        "POST",
        "/logout",
        "web-admin",
        "session",
        "auth-exit",
        "none",
        ("session",),
        ("csrf", "session required"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_app.py",),
        "Logout is current web session behavior.",
    ),
    _p(
        "web.api_readiness.index",
        "web",
        "GET",
        "/api-readiness",
        "web-admin",
        "session",
        "read-only",
        "none",
        (),
        ("session required", "aggregate-only", "no raw secret"),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_api_readiness.py",),
        "Web-admin view of the verified read-only API baseline.",
    ),
    _p(
        "web.api_tokens.index",
        "web",
        "GET",
        "/api-tokens",
        "web-admin",
        "session",
        "read-only",
        "secret-adjacent",
        (),
        ("session required", "metadata only", "no token hash", "no raw token"),
        False,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py",),
        "Lists scoped API token metadata without token hashes or raw tokens.",
    ),
    _p(
        "web.api_tokens.issue",
        "web",
        "POST",
        "/api-tokens/issue",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("api_tokens", "admin_actions"),
        ("csrf", "session required", "scope allowlist", "one-time raw token display"),
        True,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py", "tests/services/test_api_tokens.py"),
        "Issues first-slice route API tokens with raw token shown once only.",
    ),
    _p(
        "web.api_tokens.revoke",
        "web",
        "POST",
        "/api-tokens/{token_id}/revoke",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("api_tokens", "admin_actions"),
        ("csrf", "session required", "safe audit metadata"),
        True,
        "",
        False,
        "implemented",
        ("tests/web/test_api_tokens.py", "tests/services/test_api_tokens.py"),
        "Revokes scoped API tokens without secret output.",
    ),
    _p(
        "web.config_templates.save",
        "web",
        "POST",
        "/config-templates/{config_version}/save",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("config template state",),
        ("csrf", "session required", "synthetic preview", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_config_templates.py",),
        "Template changes can affect future generated configs.",
    ),
    _p(
        "web.config_templates.reset",
        "web",
        "POST",
        "/config-templates/{config_version}/reset",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("config template state",),
        ("csrf", "session required", "synthetic preview", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_config_templates.py",),
        "Template reset can affect future generated configs.",
    ),
    _p(
        "web.users.create",
        "web",
        "POST",
        "/users/new",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required", "validation"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current admin user creation route.",
    ),
    _p(
        "web.users.update",
        "web",
        "POST",
        "/users/{user_id}/edit",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required", "validation"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current admin user update route.",
    ),
    _p(
        "web.users.block",
        "web",
        "POST",
        "/users/{user_id}/block",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("users", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Current user block route.",
    ),
    _p(
        "web.users.delete",
        "web",
        "POST",
        "/users/{user_id}/delete",
        "web-admin",
        "session",
        "destructive",
        "secret-adjacent",
        ("users", "devices", "admin_actions"),
        ("csrf", "session required", "explicit confirmation candidate"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Existing route is inventoried; future UX can add stronger confirmation.",
    ),
    _p(
        "web.users.disable_vpn",
        "web",
        "POST",
        "/users/{user_id}/disable-vpn",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction"),
        True,
        "Verified live VPS disable flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py", "tests/server/test_peer_apply.py"),
        "Any behavior change requires live retest.",
    ),
    _p(
        "web.users.enable_vpn",
        "web",
        "POST",
        "/users/{user_id}/enable-vpn",
        "web-admin",
        "session",
        "remote-exec",
        "client-config-secret",
        ("devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction", "no raw secret"),
        True,
        "Verified live VPS enable/apply flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py", "tests/server/test_peer_apply.py"),
        "Any behavior change requires live retest.",
    ),
    _p(
        "web.devices.secrets",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/secrets",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        (),
        ("csrf", "session required", "user/device match", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_users.py", "tests/services/test_config_delivery.py"),
        "Config artifacts are client-config-secret.",
    ),
    _p(
        "web.devices.delete",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/delete",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction"),
        True,
        "Verified live VPS selective delete flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py", "tests/server/test_peer_apply.py"),
        "Any behavior change requires live retest.",
    ),
    _p(
        "web.users.destroy",
        "web",
        "POST",
        "/users/{user_id}/destroy",
        "web-admin",
        "session",
        "destructive",
        "operation-output",
        ("users", "devices", "remote peers", "admin_actions"),
        ("csrf", "session required", "explicit confirmation candidate", "operation contract", "redaction"),
        True,
        "Current destructive web route; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_users.py",),
        "Future API must split preview/apply/recovery.",
    ),
    _p(
        "web.email.config_send",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/email-config",
        "web-admin",
        "session",
        "secret-read",
        "client-config-secret",
        (),
        ("csrf", "session required", "user/device match", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Email config delivery sends real .conf/QR/vpn:// artifacts.",
    ),
    _p(
        "web.email.verify_start",
        "web",
        "POST",
        "/users/{user_id}/email/verify/start",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("email verification tokens", "admin_actions"),
        ("csrf", "session required", "token hash storage", "audit event", "no raw token"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Raw verification token must not be persisted or audited.",
    ),
    _p(
        "web.email.recovery_start",
        "web",
        "POST",
        "/users/{user_id}/devices/{device_id}/email-recovery/start",
        "web-admin",
        "session",
        "state-write",
        "token-raw-issue",
        ("email recovery tokens", "admin_actions"),
        ("csrf", "session required", "token hash storage", "audit event", "no raw token"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Raw recovery token must not be persisted or audited.",
    ),
    _p(
        "public_token.email_verify_submit",
        "public-token",
        "POST",
        "/email/verify",
        "public-token-holder",
        "raw token + stored hash lookup",
        "public-token-state-write",
        "public-token",
        ("email verification state",),
        ("purpose", "ttl", "one-time", "generic errors", "no raw token"),
        False,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Public token is purpose-bound, not admin auth.",
    ),
    _p(
        "public_token.email_recover_submit",
        "public-token",
        "POST",
        "/email/recover",
        "public-token-holder",
        "raw token + stored hash lookup",
        "public-token-secret-read",
        "client-config-secret",
        (),
        (
            "purpose",
            "ttl",
            "one-time",
            "user/device binding",
            "rate limit candidate",
            "audit event",
            "redaction",
            "no raw token",
        ),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_email_delivery.py",),
        "Public token can release config secret only through strict one-time recovery.",
    ),
    _p(
        "web.servers.create",
        "web",
        "POST",
        "/servers/new",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("servers", "admin_actions"),
        ("csrf", "session required", "validation", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Server connection fields remain secret-adjacent.",
    ),
    _p(
        "web.servers.update",
        "web",
        "POST",
        "/servers/{server_id}/edit",
        "web-admin",
        "session",
        "state-write",
        "secret-adjacent",
        ("servers", "admin_actions"),
        ("csrf", "session required", "validation", "no raw secret"),
        True,
        "",
        True,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Server runtime/config changes can affect live behavior.",
    ),
    _p(
        "web.servers.disable",
        "web",
        "POST",
        "/servers/{server_id}/disable",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("servers", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Disables local server record.",
    ),
    _p(
        "web.servers.sync_run",
        "web",
        "POST",
        "/servers/{server_id}/sync/run",
        "web-admin",
        "session",
        "remote-read",
        "operation-output",
        ("peer sync snapshots", "admin_actions"),
        ("csrf", "session required", "read-only command policy", "redaction"),
        True,
        "Existing peer sync reads live VPS state and updates local sync view.",
        True,
        "inventory-only",
        ("tests/web/test_servers.py", "tests/services/test_peer_inventory.py"),
        "Sync classification changes require live retest.",
    ),
    _p(
        "web.servers.unknown_peers.ignore",
        "web",
        "POST",
        "/servers/{server_id}/unknown-peers/ignore",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("peer sync ignore state", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Local ignore marker only.",
    ),
    _p(
        "web.servers.amnezia_peers.unmark",
        "web",
        "POST",
        "/servers/{server_id}/amnezia-peers/unmark",
        "web-admin",
        "session",
        "state-write",
        "none",
        ("peer sync ignore state", "admin_actions"),
        ("csrf", "session required"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/web/test_servers.py",),
        "Local unignore marker only.",
    ),
    _p(
        "web.servers.unknown_peers.remove",
        "web",
        "POST",
        "/servers/{server_id}/unknown-peers/remove",
        "web-admin",
        "session",
        "remote-exec",
        "operation-output",
        ("remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction"),
        True,
        "Existing live VPS remove flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_servers.py", "tests/server/test_peer_apply.py"),
        "Removing external peers requires careful confirmation in future API.",
    ),
    _p(
        "web.servers.missing_devices.add",
        "web",
        "POST",
        "/servers/{server_id}/missing-devices/{device_id}/add",
        "web-admin",
        "session",
        "remote-exec",
        "client-config-secret",
        ("remote peers", "admin_actions"),
        ("csrf", "session required", "operation contract", "redaction", "no raw secret"),
        True,
        "Existing live VPS add missing local device flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/web/test_servers.py", "tests/server/test_peer_apply.py"),
        "Adding a peer writes live VPS state.",
    ),
    _p(
        "web.servers.health_run",
        "web",
        "POST",
        "/servers/{server_id}/health/run",
        "web-admin",
        "session",
        "remote-read",
        "operation-output",
        ("server_health_checks", "admin_actions"),
        ("csrf", "session required", "read-only command policy", "redaction"),
        True,
        "RemoteOperationRunner read-only health check.",
        False,
        "inventory-only",
        ("tests/server/test_operation_runner.py", "tests/web/test_servers.py"),
        "Canonical read-only remote operation model.",
    ),
    _p(
        "bot.admin.approve_order",
        "bot",
        "ACTION",
        "ADMIN_APPROVE_PREFIX callback",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "remote-exec",
        "client-config-secret",
        ("orders", "devices", "remote peers", "admin_actions"),
        ("workflow.is_admin", "operation contract", "audit event", "redaction", "no raw secret"),
        True,
        "Verified live VPS approve/apply flow; not generalized API.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Verified baseline behavior contract.",
    ),
    _p(
        "bot.admin.config_resend",
        "bot",
        "ACTION",
        "ADMIN_RESEND_PREFIX callback",
        "telegram-admin",
        "Telegram identity + workflow.is_admin",
        "secret-read",
        "client-config-secret",
        (),
        ("workflow.is_admin", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py", "tests/bot/test_delivery.py"),
        "Admin resend emits config artifacts.",
    ),
    _p(
        "bot.user.config_resend",
        "bot",
        "ACTION",
        "USER_RESEND_PREFIX callback",
        "telegram-user",
        "Telegram identity + get_user_device ownership",
        "secret-read",
        "client-config-secret",
        (),
        ("ownership", "audit event", "redaction", "no raw secret"),
        True,
        "",
        False,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py", "tests/bot/test_delivery.py"),
        "User resend must remain own-device only.",
    ),
    _p(
        "bot.user.device_revoke",
        "bot",
        "ACTION",
        "USER_REVOKE_CONFIRM_PREFIX callback",
        "telegram-user",
        "Telegram identity + get_user_device ownership",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers"),
        ("ownership", "operation contract", "audit event", "redaction"),
        True,
        "Existing revoke flow removes remote peer before local revoke when configured.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Partial failure policy blocks broader API expansion.",
    ),
    _p(
        "bot.user.devices_reset",
        "bot",
        "ACTION",
        "USER_RESET_DEVICES_CONFIRM_CALLBACK",
        "telegram-user",
        "Telegram identity + user ownership",
        "remote-exec",
        "operation-output",
        ("devices", "remote peers"),
        ("ownership", "operation contract", "audit event", "redaction"),
        True,
        "Existing reset iterates owned devices; not generalized API.",
        True,
        "inventory-only",
        ("tests/bot/test_bot_workflows.py",),
        "Needs explicit partial-failure recovery before broader write API.",
    ),
    _p(
        "remote.server.health_check",
        "remote-operation",
        "OPERATION",
        "server.health.check",
        "web-admin or cli-operator or system",
        "session, cli or system",
        "remote-read",
        "operation-output",
        ("server_health_checks",),
        ("read-only command policy", "redaction", "no raw secret"),
        True,
        "RemoteOperationRunner read-only health check.",
        False,
        "inventory-only",
        ("tests/server/test_operation_runner.py", "tests/server/test_checks.py"),
        "First runner slice remains read-only.",
    ),
    _p(
        "cli.server.apply_peer_live",
        "cli",
        "COMMAND",
        "server apply-peer --apply",
        "cli-operator",
        "local shell",
        "remote-exec",
        "client-config-secret",
        ("remote peers",),
        ("explicit apply", "operation contract", "redaction", "no raw secret"),
        True,
        "Existing CLI live apply path; not future generic API.",
        True,
        "inventory-only",
        ("tests/server/test_peer_apply.py",),
        "Any behavior change requires live retest.",
    ),
    _p(
        "cli.server.revoke_peer_live",
        "cli",
        "COMMAND",
        "server revoke-peer --apply",
        "cli-operator",
        "local shell",
        "remote-exec",
        "operation-output",
        ("remote peers",),
        ("explicit apply", "operation contract", "redaction"),
        True,
        "Existing CLI live revoke path; not future generic API.",
        True,
        "inventory-only",
        ("tests/server/test_peer_apply.py",),
        "Any behavior change requires live retest.",
    ),
)


def get_surface_policy(policy_id: str) -> SurfacePolicy:
    for policy in SURFACE_POLICIES:
        if policy.policy_id == policy_id:
            return policy
    raise SurfacePolicyError(f"No surface policy for {policy_id}")


def policies_by_surface(surface: SurfaceName) -> tuple[SurfacePolicy, ...]:
    return tuple(policy for policy in SURFACE_POLICIES if policy.surface == surface)
