DEFAULT_LOCALE = "ru"
FALLBACK_LOCALE = "en"


TEXTS = {
    "ru": {
        "button.request_config": "Получить конфиг",
        "button.my_tariff": "Мой тариф",
        "button.my_traffic": "Мой трафик",
        "button.my_devices": "Мои устройства",
        "button.admin": "Админ",
        "button.approve": "Одобрить",
        "button.resend_config": "Отправить конфиг",
        "button.delete_device": "Удалить устройство",
        "button.reset_all_devices": "Сбросить все устройства",
        "button.confirm_delete": "Подтвердить удаление",
        "button.confirm_reset": "Подтвердить сброс",
        "button.pending_orders": "Заявки",
        "button.status": "Состояние",
        "button.servers": "Серверы",
        "button.integrations": "Интеграции",
        "button.traffic": "Трафик",
        "button.templates": "Шаблоны",
        "button.users": "Пользователи",
        "button.awg3_confirm": "Подтвердить AWG3",
        "button.awg2_choose": "Выбрать AWG2",
        "start.hello_name": "Здравствуйте, {first_name}.",
        "start.hello": "Здравствуйте.",
        "start.admin_role": "Доступен режим администратора.",
        "start.user_role": "Доступен режим пользователя.",
        "start.choose_action": "Выберите действие.",
        "prompt.config_version": "Выберите версию AmneziaWG для этого устройства.",
        "prompt.plan": "Выберите тариф для {config_version_label}.",
        "access.created": "Заявка #{order_id} создана.",
        "access.requested_config": "Запрошенный конфиг: {config_version_label}.",
        "access.plan": "Тариф: {plan_name}.",
        "access.admin_notice": "Администратор сможет одобрить заявку в админ-меню.",
        "my_tariff.title": "Мой тариф",
        "my_tariff.empty": "Активного тарифа пока нет.",
        "my_devices.title": "Мои устройства",
        "my_devices.empty": "Активных устройств пока нет.",
        "my_devices.external_only": (
            "Устройство ранее импортировано. Конфиг недоступен для повторной отправки: "
            "в AMN2 нет исходного client private key."
        ),
        "traffic.user_title": "Мой трафик",
        "traffic.admin_title": "Трафик пользователей",
        "traffic.no_data": "Данных о трафике пока нет.",
        "traffic.stale": "Данные о трафике могут быть устаревшими.",
        "admin.pending_title": "Заявки",
        "admin.no_pending": "Новых заявок нет.",
        "admin.users_title": "Пользователи",
        "admin.no_users": "Пользователей пока нет.",
        "admin.status_title": "Состояние AMN2",
        "admin.status_mode": "Режим: только чтение",
        "admin.status_users": "Активные пользователи: {active}; заблокированы: {blocked}",
        "admin.status_servers": "Серверы: активны {active}; degraded {degraded}",
        "admin.status_devices": "Устройства: активны {active}; отключены {disabled}",
        "admin.status_pending": "Ожидают решения: {count}",
        "admin.status_credentials": (
            "Интеграции: активны {active}; ротация нужна: {due}; "
            "истекли: {expired}; отозваны: {revoked}"
        ),
        "admin.status_vps_write": "VPS-запись: {state}",
        "admin.status_config_delivery": "Публичная выдача конфигов: {state}",
        "admin.status_public": "Публичный доступ: {state}",
        "admin.servers_title": "Серверы AMN2",
        "admin.no_servers": "Серверов пока нет.",
        "admin.server_status": "Статус: {status}",
        "admin.server_runtime": "Runtime: {runtime}",
        "admin.server_devices": "Устройства: активны {active}; всего {total}",
        "admin.server_health": "Health: {health}",
        "admin.server_latency": "Latency: {latency}",
        "admin.server_checked": "Проверено: {checked_at}",
        "admin.server_probes": "Проверки: SSH {ssh}; AWG {awg}; UDP {udp}",
        "admin.integrations_title": "Интеграции AMN2",
        "admin.no_integrations": "Интеграционных credentials пока нет.",
        "admin.integration_owner": "Владелец: {owner}",
        "admin.integration_kind": "Тип: {kind}",
        "admin.integration_purpose": "Назначение: {purpose}",
        "admin.integration_scopes": "Scopes: {scopes}",
        "admin.integration_status": "Lifecycle: {status}",
        "admin.integration_expires": "Истекает: {expires_at}",
        "admin.integration_last_used": "Последнее использование: {last_used_at}",
        "common.enabled": "включена",
        "common.disabled": "выключена",
        "common.status": "Статус",
        "common.tariff": "Тариф",
        "common.expires": "Действует до",
        "common.days_left": "Дней осталось",
        "common.config": "Конфиг",
        "common.connected": "Подключался",
        "common.yes": "да",
        "common.no": "нет",
        "common.unknown": "неизвестно",
        "common.received": "Получено",
        "common.sent": "Отправлено",
        "common.total": "Всего",
        "common.updated": "Обновлено",
        "admin.flag": "админ",
        "admin.active_devices": "активных устройств",
        "admin.total_devices": "всего устройств",
        "handler.admin_required": "Нужны права администратора.",
        "handler.unknown_language": "Неизвестный выбор языка.",
        "handler.unknown_config": "Неизвестный запрос конфига.",
        "handler.unknown_tariff": "Неизвестный запрос тарифа.",
        "handler.unknown_resend": "Неизвестный запрос повторной отправки.",
        "handler.unknown_delete": "Неизвестный запрос удаления.",
        "handler.unknown_delete_confirm": "Неизвестное подтверждение удаления.",
        "handler.device_not_found": "Устройство не найдено.",
        "handler.config_resent": "Конфиг для устройства #{device_id} отправлен повторно.",
        "handler.config_unavailable": (
            "Конфиг для этого ранее импортированного устройства недоступен для повторной "
            "отправки: в AMN2 нет исходного client private key. Устройство видно в боте "
            "и панели, но для переотправки нужен исходный файл или перевыпуск."
        ),
        "handler.confirm_device_delete": "Подтвердите удаление устройства #{device_id}.",
        "handler.confirm_reset": "Подтвердите сброс всех устройств.",
        "handler.device_removed": "Устройство #{device_id} удалено.",
        "handler.devices_removed": "Удалено устройств: {count}.",
        "handler.template_reset": "Шаблон сообщения с конфигом сброшен.",
        "handler.awg3_invalid_selection": "Invalid AWG3 selection.",
        "handler.awg3_invalid_confirmation": "Недействительное подтверждение AWG3.",
        "handler.awg3_confirm_prompt": "Подтвердите выпуск отдельного AWG3-конфига.",
        "handler.awg3_blocked": "AWG3 сейчас несовместим или недоступен для выбранной сборки.",
    },
    "en": {
        "button.request_config": "Request config",
        "button.my_tariff": "My tariff",
        "button.my_traffic": "My traffic",
        "button.my_devices": "My devices",
        "button.admin": "Admin",
        "button.approve": "Approve",
        "button.resend_config": "Resend config",
        "button.delete_device": "Delete device",
        "button.reset_all_devices": "Reset all devices",
        "button.confirm_delete": "Confirm delete",
        "button.confirm_reset": "Confirm reset",
        "button.pending_orders": "Pending orders",
        "button.status": "Status",
        "button.servers": "Servers",
        "button.integrations": "Integrations",
        "button.traffic": "Traffic",
        "button.templates": "Templates",
        "button.users": "Users",
        "button.awg3_confirm": "Confirm AWG3",
        "button.awg2_choose": "Choose AWG2",
        "start.hello_name": "Hello, {first_name}.",
        "start.hello": "Hello.",
        "start.admin_role": "Admin mode is available.",
        "start.user_role": "User mode is available.",
        "start.choose_action": "Choose an action.",
        "prompt.config_version": "Choose the AmneziaWG config version for this device.",
        "prompt.plan": "Choose tariff for {config_version_label}.",
        "access.created": "Access request #{order_id} was created.",
        "access.requested_config": "Requested config: {config_version_label}.",
        "access.plan": "Plan: {plan_name}.",
        "access.admin_notice": "An admin can approve it from the admin menu.",
        "my_tariff.title": "My tariff",
        "my_tariff.empty": "No active tariff yet.",
        "my_devices.title": "My devices",
        "my_devices.empty": "No active devices yet.",
        "my_devices.external_only": (
            "This device was imported earlier. Config resend is unavailable because "
            "AMN2 does not have the original client private key."
        ),
        "traffic.user_title": "Your traffic",
        "traffic.admin_title": "Admin traffic",
        "traffic.no_data": "No traffic data yet.",
        "traffic.stale": "Traffic data may be stale.",
        "admin.pending_title": "Pending orders",
        "admin.no_pending": "No pending orders.",
        "admin.users_title": "Admin users",
        "admin.no_users": "No users yet.",
        "admin.status_title": "AMN2 status",
        "admin.status_mode": "Mode: read-only",
        "admin.status_users": "Active users: {active}; blocked: {blocked}",
        "admin.status_servers": "Servers: active {active}; degraded {degraded}",
        "admin.status_devices": "Devices: active {active}; disabled {disabled}",
        "admin.status_pending": "Pending decisions: {count}",
        "admin.status_credentials": (
            "Integrations: active {active}; rotation due: {due}; "
            "expired: {expired}; revoked: {revoked}"
        ),
        "admin.status_vps_write": "VPS writes: {state}",
        "admin.status_config_delivery": "Public config delivery: {state}",
        "admin.status_public": "Public access: {state}",
        "admin.servers_title": "AMN2 servers",
        "admin.no_servers": "No servers yet.",
        "admin.server_status": "Status: {status}",
        "admin.server_runtime": "Runtime: {runtime}",
        "admin.server_devices": "Devices: active {active}; total {total}",
        "admin.server_health": "Health: {health}",
        "admin.server_latency": "Latency: {latency}",
        "admin.server_checked": "Checked: {checked_at}",
        "admin.server_probes": "Probes: SSH {ssh}; AWG {awg}; UDP {udp}",
        "admin.integrations_title": "AMN2 integrations",
        "admin.no_integrations": "No integration credentials yet.",
        "admin.integration_owner": "Owner: {owner}",
        "admin.integration_kind": "Kind: {kind}",
        "admin.integration_purpose": "Purpose: {purpose}",
        "admin.integration_scopes": "Scopes: {scopes}",
        "admin.integration_status": "Lifecycle: {status}",
        "admin.integration_expires": "Expires: {expires_at}",
        "admin.integration_last_used": "Last used: {last_used_at}",
        "common.enabled": "enabled",
        "common.disabled": "disabled",
        "common.status": "Status",
        "common.tariff": "Tariff",
        "common.expires": "Expires",
        "common.days_left": "Days left",
        "common.config": "Config",
        "common.connected": "Connected",
        "common.yes": "yes",
        "common.no": "no",
        "common.unknown": "unknown",
        "common.received": "Received",
        "common.sent": "Sent",
        "common.total": "Total",
        "common.updated": "Updated",
        "admin.flag": "admin",
        "admin.active_devices": "active devices",
        "admin.total_devices": "total devices",
        "handler.admin_required": "Admin access required.",
        "handler.unknown_language": "Unknown language choice.",
        "handler.unknown_config": "Unknown config request.",
        "handler.unknown_tariff": "Unknown tariff request.",
        "handler.unknown_resend": "Unknown resend request.",
        "handler.unknown_delete": "Unknown delete request.",
        "handler.unknown_delete_confirm": "Unknown delete confirmation.",
        "handler.device_not_found": "Device was not found.",
        "handler.config_resent": "Config for device #{device_id} was resent.",
        "handler.config_unavailable": (
            "Config resend is unavailable for this imported device because AMN2 does "
            "not have the original client private key. The device remains visible in "
            "the bot and panel; resending requires the original file or reissue."
        ),
        "handler.confirm_device_delete": "Confirm device deletion for device #{device_id}.",
        "handler.confirm_reset": "Confirm reset of all devices.",
        "handler.device_removed": "Device #{device_id} was removed.",
        "handler.devices_removed": "{count} device(s) were removed.",
        "handler.template_reset": "Config ready template was reset.",
        "handler.awg3_invalid_selection": "Invalid AWG3 selection.",
        "handler.awg3_invalid_confirmation": "Invalid AWG3 confirmation.",
        "handler.awg3_confirm_prompt": "Confirm issuance of a separate AWG3 config.",
        "handler.awg3_blocked": "AWG3 is currently incompatible or unavailable for the selected build.",
    },
}


def text(key: str, *, locale: str = DEFAULT_LOCALE, **values: object) -> str:
    locale_texts = TEXTS.get(locale, TEXTS[DEFAULT_LOCALE])
    fallback_texts = TEXTS[FALLBACK_LOCALE]
    template = locale_texts.get(key, fallback_texts.get(key, key))
    return template.format(**values) if values else template
