table inet amn2_spain {
    chain prerouting {
        type nat hook prerouting priority dstnat; policy accept;
        udp dport 30001 dnat ip to 172.29.251.2:30001 comment "amn2_spain:udp30001"
    }
    chain forward {
        type filter hook forward priority filter; policy accept;
        oifname "amn2spbr0" ip daddr 172.29.251.2 udp dport 30001 accept comment "amn2_spain:forward-dnat"
        iifname "amn2spbr0" ip saddr 10.212.12.0/24 accept comment "amn2_spain:forward-outbound"
        oifname "amn2spbr0" ip daddr 10.212.12.0/24 ct state established,related accept comment "amn2_spain:forward-return"
    }
    chain postrouting {
        type nat hook postrouting priority srcnat; policy accept;
        ip saddr 10.212.12.0/24 oifname != "amn2spbr0" masquerade comment "amn2_spain:masquerade"
    }
}
